### PR TITLE
Add Heroku GIS buildpack

### PR DESCRIPTION
**Pull request by andreagrandi**

### CODE REVIEW

**Comment by andreagrandi** [comment]
[Add PostGIS support to land-availability-lr app on Heroku using the proper buildpack](https://trello.com/c/ItbM1iH8/238-add-postgis-support-to-land-availability-lr-app-on-heroku-using-the-proper-buildpack)

**Comment by davidread** [comment]
I'm new to heroku, but the [docs for that buildpack](https://github.com/cyberdelia/heroku-geo-buildpack) mention you should also specify the underlying language's buildpack too e.g. heroku/python - does that apply to this case?

**Comment by andreagrandi** [comment]
Python is automatically detected by the fact requirements.txt is in the root of the project

**Comment by davidread** [comment]
Great

**Pull request merged**
