### PR TITLE
Add API for polygons from a point

### PR DESCRIPTION
**Pull request by davidread**
Used by: https://github.com/alphagov/land-availability-import/pull/28

### CODE REVIEW

**Comment by andreagrandi** [comment]
@davidread hi, is this a work in progress or a finished one?

**Comment by davidread** [comment]
@andreagrandi verbal feedback:
* we put this at /locations/ rather than /locations-at-a-point/
* change to class-based view

I'm happy to do this when we next schedule things on this work.

**Comment by andreagrandi** [comment]
I confirm my feedback and I'm happy to continue this the next time we resume our work on this

**Comment by tlwr** [comment]
I'm closing this PR as it has been open for a considerable amount of time and we're trying to cut down the number of orphaned PRs in alphagov.

**Pull request closed without merging**
